package provider

import (
	"errors"
	"regexp"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/tpretz/terraform-provider-zabbix/internal/zabbix"
)

// templateGroupsDescription documents the one field whose meaning depends on
// the server version: on 6.2+ a template belongs to template groups, below
// that to host groups. The id spaces are disjoint on 6.2+.
const templateGroupsDescription = "Group IDs this template belongs to. " +
	"On Zabbix 6.2 and later these are template group ids (zabbix_templategroup); " +
	"on 6.0/6.1 they are host group ids (zabbix_hostgroup)."

// Descriptions of the version-gated attributes. Each field simply does not
// exist on an older server -- from Zabbix 7.2 an unknown request property is a
// hard error rather than being ignored -- so the provider refuses the
// configuration rather than silently dropping it.
const (
	templateVendorNameDescription = "Template vendor name. Requires Zabbix 6.4 or later, " +
		"and must be set together with vendor_version."
	templateVendorVersionDescription = "Template vendor version. Requires Zabbix 6.4 or later, " +
		"and must be set together with vendor_name."
	templateReadmeDescription = "Template readme text, shown by the template wizard. " +
		"Requires Zabbix 7.4 or later."
	templateWizardReadyDescription = "Whether the template is ready to be offered by the " +
		"template wizard. Requires Zabbix 7.4 or later."
)

// template resource function
func resourceTemplate() *schema.Resource {
	return &schema.Resource{
		Description: "Manages a Zabbix template: a reusable collection of items, triggers, graphs and discovery rules that can be linked to many hosts.",
		Create:      resourceTemplateCreate,
		Read:        resourceTemplateRead,
		Update:      resourceTemplateUpdate,
		Delete:      resourceTemplateDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},

		// v0 -> v1: "groups" holds template group ids on Zabbix 6.2+ where it
		// previously held host group ids. See resourceTemplateStateUpgradeV0.
		SchemaVersion: 1,
		StateUpgraders: []schema.StateUpgrader{
			{
				Version: 0,
				Type:    resourceTemplateV0().CoreConfigSchema().ImpliedType(),
				Upgrade: resourceTemplateStateUpgradeV0,
			},
		},

		Schema: map[string]*schema.Schema{
			"groups": &schema.Schema{
				Type: schema.TypeSet,
				Elem: &schema.Schema{
					Type:         schema.TypeString,
					ValidateFunc: validation.StringMatch(regexp.MustCompile("^[0-9]+$"), "must be a numeric string"),
				},
				Required:    true,
				Description: templateGroupsDescription,
			},
			"host": &schema.Schema{
				Type:         schema.TypeString,
				Required:     true,
				Description:  "Technical template name, unique across the Zabbix server",
				ValidateFunc: validation.StringIsNotWhiteSpace,
			},
			"description": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Template description",
			},
			"name": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "Template display name. Defaults to the value of `host`",
			},
			"templates": &schema.Schema{
				Type:     schema.TypeSet,
				Optional: true,
				Elem: &schema.Schema{
					Type:         schema.TypeString,
					ValidateFunc: validation.StringMatch(regexp.MustCompile("^[0-9]+$"), "must be a numeric string"),
				},
				Description: "IDs of templates linked into this one, so their items and triggers are inherited",
			},
			"macro": macroSetSchema,
			"uuid": &schema.Schema{
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Template UUID, generated by Zabbix",
			},
			"vendor_name": &schema.Schema{
				Type:         schema.TypeString,
				Optional:     true,
				Description:  templateVendorNameDescription,
				RequiredWith: []string{"vendor_version"},
			},
			"vendor_version": &schema.Schema{
				Type:         schema.TypeString,
				Optional:     true,
				Description:  templateVendorVersionDescription,
				RequiredWith: []string{"vendor_name"},
			},
			"readme": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Description: templateReadmeDescription,
			},
			"wizard_ready": &schema.Schema{
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     false,
				Description: templateWizardReadyDescription,
			},
		},
	}
}

func dataTemplate() *schema.Resource {
	return &schema.Resource{
		Description: "Looks up an existing Zabbix template by technical name or display name.",
		Read:        dataTemplateRead,

		Schema: map[string]*schema.Schema{
			"groups": &schema.Schema{
				Type: schema.TypeSet,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
				Computed:    true,
				Description: templateGroupsDescription,
			},
			"host": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "Technical template name. Give one of `host` or `name`",
			},
			"description": &schema.Schema{
				Type:        schema.TypeString,
				Description: "Template description",
				Computed:    true,
			},
			"name": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "Template display name. Give one of `host` or `name`",
			},
			// templateRead is shared with the resource and unconditionally sets
			// "templates"; without a matching attribute here helper/schema
			// panics with "Invalid address to set", which crashed the provider
			// on every use of this data source.
			"templates": &schema.Schema{
				Type: schema.TypeSet,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
				Computed:    true,
				Description: "IDs of templates linked into this one",
			},
			"macro": macroSetSchema,
			"uuid": &schema.Schema{
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Template UUID, generated by Zabbix",
			},
			"vendor_name": &schema.Schema{
				Type:        schema.TypeString,
				Computed:    true,
				Description: templateVendorNameDescription,
			},
			"vendor_version": &schema.Schema{
				Type:        schema.TypeString,
				Computed:    true,
				Description: templateVendorVersionDescription,
			},
			"readme": &schema.Schema{
				Type:        schema.TypeString,
				Computed:    true,
				Description: templateReadmeDescription,
			},
			"wizard_ready": &schema.Schema{
				Type:        schema.TypeBool,
				Computed:    true,
				Description: templateWizardReadyDescription,
			},
		},
	}
}

// terraform resource create handler
func resourceTemplateCreate(d *schema.ResourceData, m interface{}) error {
	api := m.(*zabbix.API)

	item, err := buildTemplateObject(d, m)
	if err != nil {
		return err
	}
	items := []zabbix.Template{*item}

	err = api.TemplatesCreate(items)

	if err != nil {
		return err
	}

	log.Trace("crated template: %+v", items[0])

	d.SetId(items[0].TemplateID)

	return resourceTemplateRead(d, m)
}

// templateGroupSelectParam names the template.get parameter that returns group
// membership. Zabbix 7.2 removed "selectGroups" (deprecated since 6.2) in
// favour of "selectTemplateGroups"; on 7.2+ the old name is silently ignored,
// so the template reads back with no groups rather than erroring.
func templateGroupSelectParam(m interface{}) string {
	if m.(*zabbix.API).Config.Version >= zabbix.V72 {
		return "selectTemplateGroups"
	}
	return "selectGroups"
}

// terraform template read handler (data source)
func dataTemplateRead(d *schema.ResourceData, m interface{}) error {

	params := zabbix.Params{
		"filter":                    map[string]interface{}{},
		"selectMacros":              "extend",
		"selectParentTemplates":     "extend",
		templateGroupSelectParam(m): "extend",
	}

	if v := d.Get("host").(string); v != "" {
		params["filter"].(map[string]interface{})["host"] = v
	}

	if v := d.Get("name").(string); v != "" {
		params["filter"].(map[string]interface{})["name"] = v
	}

	if len(params["filter"].(map[string]interface{})) < 1 {
		return errors.New("no filter parameters provided")
	}
	log.Debug("Lookup of template with: %#v", params)

	if err := templateRead(d, m, params); err != nil {
		return err
	}
	return dataSourceFound(d, "template", "host", "name")
}

// terraform template read handler (resource)
func resourceTemplateRead(d *schema.ResourceData, m interface{}) error {
	log.Debug("Lookup of template with id %s", d.Id())

	return templateRead(d, m, zabbix.Params{
		"templateids":               d.Id(),
		"selectMacros":              "extend",
		"selectParentTemplates":     "extend",
		templateGroupSelectParam(m): "extend",
	})
}

// generic template read function
func templateRead(d *schema.ResourceData, m interface{}, params zabbix.Params) error {
	api := m.(*zabbix.API)

	templates, err := api.TemplatesGet(params)

	if err != nil {
		return err
	}

	if len(templates) < 1 {
		d.SetId("")
		return nil
	}
	if len(templates) > 1 {
		return errors.New("multiple templates found")
	}
	t := templates[0]

	log.Debug("Got template: %+v", t)

	d.Set("description", t.Description)
	d.Set("host", t.Host)
	d.Set("name", t.Name)
	d.Set("macro", flattenMacros(t.UserMacros))
	d.Set("groups", flattenHostGroupIds(t.Groups))
	d.Set("templates", flattenTemplateIds(t.ParentTemplates))
	d.Set("uuid", t.UUID)

	// The version-gated attributes come back as nil from a server that does
	// not have them. They are still written to state, as their zero value:
	// buildTemplateObject refuses to accept a non-zero value on such a
	// server, so the zero value is the only thing a configuration can hold,
	// and writing it keeps a freshly imported resource identical to a
	// freshly applied one.
	d.Set("vendor_name", derefOr(t.VendorName, ""))
	d.Set("vendor_version", derefOr(t.VendorVersion, ""))
	d.Set("readme", derefOr(t.Readme, ""))
	d.Set("wizard_ready", derefOr(t.WizardReady, "0") == "1")

	d.SetId(t.TemplateID)

	return nil
}

// build a template object from terraform data
//
// The vendor and wizard attributes only exist from a given server version on,
// and Zabbix 7.2 turned an unknown request property into a hard error, so each
// is written only when the server has it. Configuring one below its version is
// an error here rather than a silently ignored setting.
func buildTemplateObject(d *schema.ResourceData, m interface{}) (*zabbix.Template, error) {
	api := m.(*zabbix.API)

	item := zabbix.Template{
		Description:     d.Get("description").(string),
		Name:            d.Get("name").(string),
		Host:            d.Get("host").(string),
		Groups:          buildHostGroupIds(d.Get("groups").(*schema.Set)),
		LinkedTemplates: buildTemplateIds(d.Get("templates").(*schema.Set)),
	}

	vendorName := d.Get("vendor_name").(string)
	vendorVersion := d.Get("vendor_version").(string)
	if api.Config.Version >= zabbix.V64 {
		item.VendorName = &vendorName
		item.VendorVersion = &vendorVersion
	} else if vendorName != "" || vendorVersion != "" {
		return nil, errors.New("vendor_name and vendor_version require Zabbix 6.4 or later")
	}

	readme := d.Get("readme").(string)
	wizardReady := "0"
	if d.Get("wizard_ready").(bool) {
		wizardReady = "1"
	}
	if api.Config.Version >= zabbix.V74 {
		item.Readme = &readme
		item.WizardReady = &wizardReady
	} else if readme != "" || wizardReady == "1" {
		return nil, errors.New("readme and wizard_ready require Zabbix 7.4 or later")
	}

	item.UserMacros = macroGenerate(d)
	return &item, nil
}

// terraform update resource handler
func resourceTemplateUpdate(d *schema.ResourceData, m interface{}) error {
	api := m.(*zabbix.API)

	item, err := buildTemplateObject(d, m)
	if err != nil {
		return err
	}
	item.TemplateID = d.Id()

	// templates may need a bit extra effort
	if d.HasChange("templates") {
		old, new := d.GetChange("templates")
		diff := old.(*schema.Set).Difference(new.(*schema.Set))

		// removals, we need to unlink and clear.
		//
		// Filtered through existingTemplateIds for the same reason
		// resourceHostUpdate does it: Terraform will happily destroy a
		// zabbix_template in the same apply that unlinks it, and from Zabbix
		// 7.0 an unknown object id in templates_clear is a hard error rather
		// than a no-op. Deleting a template unlinks it anyway, so dropping the
		// dead ids loses nothing.
		if diff.Len() > 0 {
			toClear, err := existingTemplateIds(api, diff)
			if err != nil {
				return err
			}
			if len(toClear) > 0 {
				item.TemplatesClear = toClear
			}
		}
	}

	items := []zabbix.Template{*item}

	if err := api.TemplatesUpdate(items); err != nil {
		return err
	}

	return resourceTemplateRead(d, m)
}

// terraform delete handler
func resourceTemplateDelete(d *schema.ResourceData, m interface{}) error {
	api := m.(*zabbix.API)
	return api.TemplatesDeleteByIds([]string{d.Id()})
}
