package zabbix

// Template represent Zabbix Template type returned from Zabbix API
// https://www.zabbix.com/documentation/3.2/manual/api/reference/template/object
type Template struct {
	TemplateID string `json:"templateid,omitempty"`
	Host       string `json:"host"`
	// Description carries no omitempty deliberately: with it, removing the
	// attribute from a configuration sent nothing at all, the server kept the
	// old text and the next read put it straight back, so a template's
	// description could be set but never cleared.
	Description string `json:"description"`
	// Name, in contrast, must keep omitempty: Zabbix rejects an empty
	// visible name and defaults it to "host" when the property is absent,
	// which is what the schema's Optional+Computed "name" relies on.
	Name string `json:"name,omitempty"`

	// UUID is generated by Zabbix on create. It is accepted on create (a
	// UUIDv4 is required) but the provider never writes it: prepTemplates
	// clears it so it is read-only in practice.
	UUID string `json:"uuid,omitempty"`

	// Version-gated properties. Each is a pointer so that "leave alone"
	// (nil, below the version that has the field) is distinguishable from
	// "set to empty" (a pointer to ""), which is how the field is cleared.
	// Sending any of them to a server that predates it is a hard error from
	// Zabbix 7.2 on and silently ignored before, so the caller must only
	// populate them when api.Config.Version allows.

	// VendorName/VendorVersion are 6.4+, and Zabbix requires both to be set
	// or both to be empty.
	VendorName    *string `json:"vendor_name,omitempty"`
	VendorVersion *string `json:"vendor_version,omitempty"`

	// Readme and WizardReady ("0"/"1") are 7.4+.
	Readme      *string `json:"readme,omitempty"`
	WizardReady *string `json:"wizard_ready,omitempty"`
	// Groups carries template group ids on Zabbix 6.2+ and host group ids
	// below that; the wire property is "groups" either way. The id types are
	// structurally identical ({"groupid": "..."}), so HostGroupIDs is reused.
	Groups          HostGroupIDs `json:"groups"`
	UserMacros      Macros       `json:"macros"`
	LinkedTemplates TemplateIDs  `json:"templates,omitempty"`
	ParentTemplates TemplateIDs  `json:"parentTemplates,omitempty"`
	TemplatesClear  TemplateIDs  `json:"templates_clear,omitempty"`
	LinkedHosts     []string     `json:"hosts,omitempty"`

	// Group membership on read. Zabbix 7.2 removed "selectGroups" in favour of
	// "selectTemplateGroups"/"selectHostGroups", which answer under different
	// property names. TemplatesGet folds these back into Groups so callers see
	// one field; the write path always uses "groups".
	TemplateGroups HostGroupIDs `json:"templategroups,omitempty"`
	HostGroups     HostGroupIDs `json:"hostgroups,omitempty"`
}

// Templates is an Array of Template structs.
type Templates []Template

// TemplateID use with host creation
type TemplateID struct {
	TemplateID string `json:"templateid"`
}

// TemplateIDs is an Array of TemplateID structs.
type TemplateIDs []TemplateID

// TemplatesGet Wrapper for template.get
// https://www.zabbix.com/documentation/3.2/manual/api/reference/template/get
func (api *API) TemplatesGet(params Params) (res Templates, err error) {
	if _, present := params["output"]; !present {
		params["output"] = "extend"
	}
	err = api.CallWithErrorParse("template.get", params, &res)
	for i := range res {
		if len(res[i].Groups) > 0 {
			continue
		}
		if len(res[i].TemplateGroups) > 0 {
			res[i].Groups = res[i].TemplateGroups
		} else if len(res[i].HostGroups) > 0 {
			res[i].Groups = res[i].HostGroups
		}
	}
	return
}

// TemplateGetByID Gets template by Id only if there is exactly 1 matching template.
func (api *API) TemplateGetByID(id string) (template *Template, err error) {
	templates, err := api.TemplatesGet(Params{"templateids": id})
	if err != nil {
		return
	}

	if len(templates) == 1 {
		template = &templates[0]
	} else {
		e := ExpectedOneResult(len(templates))
		err = &e
	}
	return
}

// prepTemplates strips the properties that must never be written back:
// the read-only group mirrors, which template.create/update reject as unknown
// object properties, and the server-generated uuid.
func prepTemplates(templates Templates) {
	for i := range templates {
		templates[i].TemplateGroups = nil
		templates[i].HostGroups = nil
		templates[i].UUID = ""
	}
}

// TemplatesCreate Wrapper for template.create
// https://www.zabbix.com/documentation/3.2/manual/api/reference/template/create
func (api *API) TemplatesCreate(templates Templates) (err error) {
	prepTemplates(templates)
	response, err := api.CallWithError("template.create", templates)
	if err != nil {
		return
	}

	result := response.Result.(map[string]interface{})
	templateids := result["templateids"].([]interface{})
	for i, id := range templateids {
		templates[i].TemplateID = id.(string)
	}
	return
}

// TemplatesUpdate Wrapper for template.update
// https://www.zabbix.com/documentation/3.2/manual/api/reference/template/update
func (api *API) TemplatesUpdate(templates Templates) (err error) {
	prepTemplates(templates)
	_, err = api.CallWithError("template.update", templates)
	return
}

// TemplatesDelete Wrapper for template.delete
// Cleans ApplicationID in all apps elements if call succeed.
// https://www.zabbix.com/documentation/3.2/manual/api/reference/template/delete
func (api *API) TemplatesDelete(templates Templates) (err error) {
	templatesIds := make([]string, len(templates))
	for i, template := range templates {
		templatesIds[i] = template.TemplateID
	}

	err = api.TemplatesDeleteByIds(templatesIds)
	if err == nil {
		for i := range templates {
			templates[i].TemplateID = ""
		}
	}
	return
}

// TemplatesDeleteByIds Wrapper for template.delete
// Use template's id to delete the template
// https://www.zabbix.com/documentation/3.2/manual/api/reference/template/delete
func (api *API) TemplatesDeleteByIds(ids []string) (err error) {
	response, err := api.CallWithError("template.delete", ids)
	if err != nil {
		return
	}

	result := response.Result.(map[string]interface{})
	templateids := result["templateids"].([]interface{})
	if len(ids) != len(templateids) {
		err = &ExpectedMore{len(ids), len(templateids)}
	}
	return
}
